#ifndef SIMULATION_PARAMETERS_H
#define SIMULATION_PARAMETERS_H

const int NUMBER_OF_NODES = 50;
const int MIN_PEERS_CONNECTED = 3;
const int MAX_PEERS_CONNECTED = 6;

const int RANDOM_GENERATOR_SEED = 13;


#endif // NODE_CONSTANTS_H