#ifndef SIMULATION_PARAMETERS_H
#define SIMULATION_PARAMETERS_H

const int NUMBER_OF_NODES = 50;
const int MIN_PEERS_CONNECTED = 3;
const int MAX_PEERS_CONNECTED = 6;

const int RANDOM_GENERATOR_SEED = 13;

const int LIGHT_SPEED_DELAY = 20; //TODO : to be taken from uniform districution

const double TRANSACTION_INTERARRIVAL_MEAN = 6000;

const int INITIAL_BALANCE = 101;

const int TRANSACTION_SIZE_BYTES = 1024;

const int BLOCK_INTERARRIVAL_TIME = 600000;

#endif // SIMULATION_PARAMETERS_H